language: python
python:
    - 3.6
install:
    - pip install boto3
    - pip install utils
    - pip install moto
    - pip install coverage
addons:
    sonarcloud:
        organization: "usdot-jpo-sdc"
script: 
    - coverage erase
    - sonar-scanner -X -D sonar.login=$SONAR_TOKEN
